name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  issues: write 

jobs:

  tests:
    name: Run Unit Tests with Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests with Coverage
        run: |
          source .venv/bin/activate
          coverage run --source=src -m unittest discover -s tests
          coverage report
          coverage xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

  # Lintowanie kodu
  lint:
    name: Lint Code with SuperLinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SuperLinter
        uses: github/super-linter@v5
        env:
          VALIDATE_PYTHON: true 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  todo:
    name: Create Issues from TODOs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Issues from TODOs
        uses: alstr/todo-to-issue-action@v1
        with:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
